default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: postgresql://postgres:nuarfiigienic@db.faoicgrgcbifleumdzbb.supabase.co:5432/postgres

development:
  <<: *default
  database: vacation_suggestions_api_development

test:
  <<: *default
  database: vacation_suggestions_api_test

production:
  <<: *default
  database: vacation_suggestions_api_production
  username: vacation_suggestions_api
  password: <%= ENV["VACATION_SUGGESTIONS_API_DATABASE_PASSWORD"] %>
