default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: postgresql://neondb_owner:npg_StYVO2uKad6Q@ep-bold-thunder-a2v1armx-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require

development:
  <<: *default
  database: vacation_suggestions_api_development

test:
  <<: *default
  database: vacation_suggestions_api_test

production:
  <<: *default
  database: vacation_suggestions_api_production
  username: vacation_suggestions_api
  password: <%= ENV["VACATION_SUGGESTIONS_API_DATABASE_PASSWORD"] %>
#g;lamgsa
